spring:
  datasource:
    driverClassName: org.h2.Driver
    password: testing
    url: jdbc:h2:~/product_db;DB_CLOSE_ON_EXIT=FALSE
    username: testing
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update