spring:
  application:
    name: PRODUCT
  datasource:
    password: testing
    username: testing
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/product_db;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}